### ISSUE TITLE
Allow creating a new Cluster with alive and down nodes

### ISSUE THREAD

**Issue by nfo** [yandex/go-hasql#5]
*Scenario*:
- I call `hasql.NewCluster` with three nodes. One node is unreachable ("context deadline exceeded"). 
- All further calls to `Cluster.WaitFor*` return an error.
- Calls to `Cluster.Alive`, `Cluster.Primary*` and `Cluster.Standby*` return nil.

*Expected*: Being able to create a cluster which includes unreachable nodes and still be able to query the alive nodes.

**Comment by vtolstov** [comment]
do you plan to fix this ?

**Comment by bbrodriges** [comment]
Yes, there will be fix soon

**Comment by vtolstov** [comment]
any news ?=)

**Comment by bbrodriges** [comment]
> any news ?=)

Upon deep inspection I can assume that this is a problem with `context.Context` provided to `WaitFor/Alive/Primary`. Provided context must be greater than `refreshInterval`+`refreshTimeout` duration, in other case `ContextDeadlineExceeded` will be returned.

As I can see there is no problem with partially available cluster in `checkNodes` function - https://github.com/yandex/go-hasql/blob/master/check_nodes.go#L96

Can you provide a bit more context to problem, a reproducer may be?

**Comment by bbrodriges** [comment]
Please read this [comment](https://github.com/yandex/go-hasql/blob/45d4bcbb4ed211cd3acb07f49b290a7d87e03858/e2e_test.go#L158-L162), it may help you to fix the issue.
